server:
 servlet:
   context-path: /
   
openapi:
 service:
   title: amazon-services doc #title that you will want to display in the swagger ui
   version: 1.0.0 
   url: http://localhost:8765 #api gateway url
springdoc:
 api-docs:
   path: /amazon-services/v3/api-docs #these urls will used to load the swagger ui of this service by the api gateway
 swagger-ui:
   path: /amazon-services/swagger-ui.html